import TodoList from "@/components/TodoList";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Todos',
    description: 'Generated by create next app',
    viewport: {
        width: 'device-width',
        initialScale: 1,
        maximumScale: 1,
    }
};

interface Props
{
    children: React.ReactNode;
}

function TodoLayout({ children }: Props)
{
    return (
        <div className="flex gap-8">
            {/* @ts-expect-error Async Server Component */}
            <TodoList />
            <div className="flex flex-col w-[500px] item-center">{children}</div>
        </div>
    );
}

export default TodoLayout;
