import { ReactNode } from "react";
import './globals.css';
import { Metadata } from "next";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: {
    default: 'Nexto',
    template: '%s | Nexto'
  },
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  }
};

interface Props
{
  children: ReactNode;
}

export default function RootLayout({
  children,
}: Props)
{
  return (
    <html
      lang="ko"
      className="scroll-smooth antialiased"
      suppressHydrationWarning
    >
      <head />
      <body
        className="bg-element1 text-text1 min-h-screen font-pretendard overflow-y-auto"
      >
        <Header />
        <main className="flex justify-center w-full h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
