import Search from "@/components/Search";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Search',
    description: 'Generated by create next app',
    viewport: {
        width: 'device-width',
        initialScale: 1,
        maximumScale: 1,
    }
};

interface Props
{
    children: React.ReactNode;
}

function SearchLayout({ children }: Props)
{
    return (
        <div className="flex flex-col">
            <div className="flex justify-center mb-4">
                <h1>Search</h1>
            </div>
            <div className="flex flex-col flex-1 gap-2">
                <Search />
                <div className="w-full">{children}</div>
            </div>
        </div>
    );
}

export default SearchLayout;
